apiVersion: v1
kind: ReplicationController
metadata:
  name: registry
  labels:
    name: registry
spec:
  replicas: 1
  selector:
    name: registry
  template:
    metadata:
      labels:
        name: registry
    spec:
      containers:
      - name: registry
#        image: caicloud/harbor_registry:2.3.0
        image: hleon256/registry:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        - containerPort: 5001
        volumeMounts:
        - name: storage
          mountPath: /storage
        env:
        - name: GODEBUG
          value: netdns=cgo
        - name: TOKEN_URL
          value: http://c9t24960.itcs.hpecorp.net:31366
        command: ["/bin/sh", "-c"]
        args: ["MYVARS='$TOKEN_URL';envsubst \"$MYVARS\" < /etc/registry/config.yml.template > /etc/registry/config.yml;/bin/registry serve /etc/registry/config.yml"]
      volumes:
      - name: storage
        emptyDir: {}
